### ISSUE TITLE
Google can't add extension error.

### ISSUE THREAD

**Issue by RealBrianOG** [10101000/Steam-AutoCraft#10]
https://gyazo.com/c5ed1efab12f95db303e754728c85de3

**Comment by 10101000** [comment]
Hi, Steam-AutoCraft requires the [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo) extension for Chrome. This error occurs if Tampermonkey is disabled or not installed.
