### ISSUE TITLE
Auto Craft Grayed out?

### ISSUE THREAD

**Issue by blackhat576** [10101000/Steam-AutoCraft#12]

**Comment by 10101000** [comment]
Can you provide more information? I've just tested using my personal account and it seems to be working as expected. The button is designed to be grayed out if there aren't enough cards available to craft a given badge. If enough cards are available please provide the following information:

- Browser version.
- Tampermonkey/Greasemonkey version.
- Steam-AutoCraft version.
- Java console log when loading the Badges/Gamecards page.

Please ensure that you're using the latest version of Steam-AutoCraft from this repository.

**Comment by 10101000** [comment]
Closing due to lack of reply.
