### ISSUE TITLE
can't click auto craft button

### ISSUE THREAD

**Issue by Reda2004** [10101000/Steam-AutoCraft#14]
Hey guys, I'm trying to click the auto craft all badges button but all I can do is click the settings button. Any help? 
Thanks

**Comment by 10101000** [comment]
Hi, the button will be disabled unless you have enough trading cards to craft a badge. If you do have at least 1 full set of cards please include the following information:

- Browser make and version.
- Version of Tampermonkey/Greasemonkey.
- Console output after refresh of page.

**Comment by 10101000** [comment]
No response. Closing.
