### ISSUE TITLE
Autocraft icon does not appear as usual.

### ISSUE THREAD

**Issue by easonschmitt** [10101000/Steam-AutoCraft#15]
When I get access to the badge page, there is no auto craft icon. Besides, there is lag even if it starts to autocraft

**Comment by easonschmitt** [comment]
I visit steamcommunity through https

**Comment by 10101000** [comment]
Hi,

It's nearly impossible for me to help with such little information provided. It sounds like the script is improperly installed. Please include:

- Browser version
- AutoCraft Script version
- TamperMonkey/GreaseMonkey version
- Javascript console logs from the Badges/Gamecards page

Some troubleshooting steps might be to disable all other Steam modifications, remove and re-install per the instructions [here](github.com/10101000/Steam-AutoCraft).

**Comment by 10101000** [comment]
No response, closing.
