### ISSUE TITLE
Button grayed 

### ISSUE THREAD

**Issue by wineasy** [10101000/Steam-AutoCraft#5]
Hello,

First of thanks for this script, i was looking for such script since long time now, i installed it on both mozilla/chrome but i got the same problem, the button is grayed: https://gyazo.com/ddd465f9aaba8ff6947abdcb17096e23

Did i missed something ?

**Comment by 10101000** [comment]
Hi,

This is very strange, are you using any Steam plugins aside from Steam-AutoCraft? If yes, please disable them one by one to determine if there is a conflict. I am unable re-produce this behavior. In my tests the button is activated as expected once a link with `class="badge_craft_button"` and div with `class="gamecard_badge_progress"` or `class="badge_progress_tasks"` is detected. I've also tested changing my language to French and the button is activated so this isn't the problem. Once you've ruled out a conflict with another plugin, please use the Google Chrome [inspect feature](https://developers.google.com/web/tools/chrome-devtools/inspect-styles/) to search the page for these classes.

**Comment by wineasy** [comment]
I'm using SIH and Enhanced Steam on Chrome but no script on Mozilla except this one and of course greasemonkey (https://gyazo.com/33048b43f2117b8632e487f396c26c80) and the same problem appear :/

btw, hanks for the fast reply

**Comment by 10101000** [comment]
The "toothed wheel" settings look correct. I'd initially thought that the Award Badge might be a problem as well but tested it on my secondary Steam account and couldn't find a problem. The code must not be able to find `class="badge_craft_button"` or `class="gamecard_badge_progress"`. Can you verify that they exist on the page? Also can you click into Stigmat badge to verify that the button is enabled there?

**Comment by wineasy** [comment]
If i click right and "source code" i can see this part; http://pastebin.com/RMnuSJ9G

If i click on Stigmat then the button isn't grayed: https://gyazo.com/ddb10a17f40c5a4e66b17e58b139b351

**Comment by 10101000** [comment]
OK, the badge_craft_button link is correct. However, I've mistakenly requested that you search for the wrong class. The gamecard_badge_progress class appears on the gamecard page (the one that works for you) not the badges page. On the badges page, look for `<div class="badge_progress_tasks badge_cards">`, this is how it appears in the source on my accounts.

**Comment by wineasy** [comment]
Yep, i seen it too:
<div class="badge_progress_tasks badge_cards">
						<div class="badge_progress_card_ctn">

**Comment by TheRealKerel** [comment]
i have the same problem :(

**Comment by 10101000** [comment]
I'm at a loss, I can't fix a problem that I can't replicate. Does the error console show any errors? Are you using any security software that scans or modifies HTTP connections or limits script execution? You might try to reset Chrome's profile by renaming it: http://techin.oureverydaylife.com/completely-reset-google-chrome-15672.html

**Comment by 10101000** [comment]
You're right, it appears to be the **_Steam Awards Nomination Committee 2016_** badge but only if completed at 100xp. I'm investigating a fix.

**Comment by wineasy** [comment]
Ah that's a very good news !!
Thanks for the work :)

**Comment by 10101000** [comment]
This should be fixed with version 1.4.9. Will you please update and confirm?

**Comment by TheRealKerel** [comment]
Now it works perfectly fine. Thank you very much!

**Comment by wineasy** [comment]
The button isn't grayed anymore so it should work now
Thanks a lot ;-)

**Comment by 10101000** [comment]
Thanks for the confirmations!
