### ISSUE TITLE
Sale cards crafted too?

### ISSUE THREAD

**Issue by nekomimibadik** [10101000/Steam-AutoCraft#6]
I want to use this to craft badges so i can sell sale cards, but i guess this script will craft sale cards right away?

**Comment by 10101000** [comment]
Please read the usage documentation: https://github.com/10101000/Steam-AutoCraft/blob/master/README.md

> The following settings are now available: Page Refresh Timeout, Card Refresh Timeout, and **Game ID Blacklist**. Page and Card refresh values both use the milliseconds metric. The Page refresh occurs after all badges have been crafted and is longer than the Card refresh. The card refresh occurs after a single badge as been crafted. **The Game ID Blacklist value uses the format of id1,id2, i.e. 12345,67890. Any ID in the list will be excluded from automatic crafting when recursive mode is executed from the badges page.**

**Comment by nekomimibadik** [comment]
Thanks for the blacklist note but how do i know the id for sale cards?

**Comment by 10101000** [comment]
The ID appears within the URL for the badge link. For example, the **_Summer Sale 2016 Badge_** URL is http://steamcommunity.com/id/user/gamecards/**480730**. Hence the ID is 480730.
