### ISSUE TITLE
[BUG] Blacklist function not working probably

### ISSUE THREAD

**Issue by HKZonda** [10101000/Steam-AutoCraft#7]
Hi

1st of all thanks for creating this awesome script for saving everyone's time out there
Much applause 
I found a problem when I was using the script today
The problem is after I blacklisted the sale badge id and auto crafted 200+ sets of cards
I figured out 6 sets of the sale cards were crafted as well after the whole process
So I guess something maybe bugged

Edited: After some observation, it seems that the "Craft" button for the blacklisted badge was not disabled after the automatic refresh of the badge page, it was shown on screen for a glimpse at least

**Comment by 10101000** [comment]
Thanks for the report. I'd tested this functionality after making the most recent changes but perhaps something has changed since then. I'll look into it.

**Comment by 10101000** [comment]
I've identified and fixed the problem in version 1.4.10.
