### ISSUE TITLE
There was a problem purchasing your item. The listing may have been removed. Refresh the page and try again.

### ISSUE THREAD

**Issue by SourceM7** [10101000/Steam-AutoCraft#8]
There was a problem purchasing your item. The listing may have been removed. Refresh the page and try again.

**Comment by 10101000** [comment]
Hi, This script doesn't purchase anything. It doesn't even run on the Steam Market pages. It only runs on the gamecard and badges pages:

`// @include      /^https?:\/\/steamcommunity\.com\/+(id\/+[A-Za-z0-9$-_.+!*'(),]+|profiles\/+[0-9]+)\/+(badges\/?|gamecards\/+[0-9]+\/?).*$/`

I don't understand how you could see this error during the badge crafting process unless perhaps you're using another Steam modification plugin/script. If you're using additional Steam modifications, please disable and try again.
