### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by chris050999** [10101000/Steam-AutoCraft#9]
Using Tampermonkey on chrome.
Script does not run properly and therefore no button appears.

"Syntax error @ "Steam-AutoCraft"!
##########################
JSHINT output:
script: (W033) Missing semicolon on line: 72 at character: 92
script: (W033) Missing semicolon on line: 191 at character: 8
script: (W018) Confusing use of '!' on line: 197 at character: 8
script: (W018) Confusing use of '!' on line: 203 at character: 8
script: (W033) Missing semicolon on line: 233 at character: 11
script: (W033) Missing semicolon on line: 248 at character: 11
script: (W004) 'position' is already defined on line: 289 at character: 13
script: (W004) 'x' is already defined on line: 290 at character: 13
script: (W004) 'y' is already defined on line: 291 at character: 13
script: (W033) Missing semicolon on line: 298 at character: 11
script: (W033) Missing semicolon on line: 313 at character: 11
##########################

SyntaxError: Unexpected token ILLEGAL
    at eval (native)
    at <anonymous>:2:297
    at Object.b [as F_c] (<anonymous>:2:142)
    at Object.R.E_u (<anonymous>:2:467)
    at x (eval at <anonymous> (unknown source), <anonymous>:57:419)
    at E (eval at <anonymous> (unknown source), <anonymous>:56:166)
    at Object.Qa.create (eval at <anonymous> (unknown source), <anonymous>:64:282)
    at z (eval at <anonymous> (unknown source), <anonymous>:13:88)VM1287:57 (anonymous function)
VM1287:57 Uncaught SyntaxError: Unexpected token ILLEGAL"

**Comment by 10101000** [comment]
Hi. I believe that Release 1.6.1 has resolved the problem. Please confirm.
